spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store
    username: root
    password: l15673711635
    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 15MB

server:
  port: 80

mybatis:
  mapper-locations: classpath:mapper/*.xml

# Spring读取配置文件中数据
user.address.max-count: 20